version: '3.8'

services:
  dotnet8webapi:
    image: ${DOCKER_REGISTRY-}dotnet8webapi
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
